name: grocery_store
description: grocery store application
dependencies:
    angular: ">=1.0.0 <2.0.0"
    polymer: any
    paper_elements: ">=0.5.0 <0.6.0"
    angular_node_bind: any
dependency_overrides:
    html5lib: '>=0.10.0 <0.13.0'
    args: '>=0.10.0 <=0.12.1'
    code_transformers: '>=0.1.4+2 <0.3.0'
    observe: 0.12.1+1
dev_dependencies:
  unittest: any
transformers:
- angular
