name: grocery_store
description: grocery store application
dependencies:
    angular: ">=1.0.0 <2.0.0"
    polymer: 0.15.1+5
    paper_elements: ">=0.5.0 <0.6.0"
    angular_node_bind: any
    web_components: any
dependency_overrides:
    html5lib: 0.12.0
    args: 0.12.1
    code_transformers: 0.2.3
    observe: 0.12.1+1
dev_dependencies:
  unittest: any
transformers:
- angular
