name: grocery_store
description: grocery store application
dependencies:
    angular: any
    polymer: any
    paper_elements: any
    angular_node_bind: any
dev_dependencies:
  unittest: any
transformers:
- angular
